from gym.envs.classic_control.cartpole import CartPoleEnv
from gym.envs.classic_control.mountain_car import MountainCarEnv
from gym.envs.classic_control.continuous_mountain_car import Continuous_MountainCarEnv
from gym.envs.classic_control.pendulum import PendulumEnv
from gym.envs.classic_control.acrobot import AcrobotEnv
from gym.envs.classic_control.continuous_action_mountain_car import Continuous_Action_MountainCarEnv

from gym.envs.classic_control.mountain_car_state_velovisual import state_velovisual_MountainCarEnv
from gym.envs.classic_control.continuous_mountain_car_state_velovisual import state_velovisual_Continuous_MountainCarEnv
from gym.envs.classic_control.continuous_action_mountain_car_state_velovisual import state_velovisual_Continuous_Action_MountainCarEnv
from gym.envs.classic_control.mountain_carJinghua import MountainCarJinghuaEnv

from gym.envs.classic_control.mountain_carJinghua_original import MountainCarJinghuaOriginalEnv
from gym.envs.classic_control.cue_continuous_mountain_car import CueContinuousMountainCarEnv